# Generated by Django 3.2 on 2021-11-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Head_Name', models.CharField(max_length=100)),
                ('Amount', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Head_Name', models.CharField(max_length=100)),
                ('Amount', models.CharField(max_length=100)),
            ],
        ),
    ]
