# Generated by Django 3.2 on 2021-11-02 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211102_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='Expans_type',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='credit',
            name='Vaucher',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='debit',
            name='Expans_type',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='debit',
            name='Vaucher',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='credit',
            name='Date',
            field=models.DateField(default=datetime.date(2021, 11, 3), verbose_name=datetime.date(2021, 11, 3)),
        ),
        migrations.AlterField(
            model_name='debit',
            name='Date',
            field=models.DateField(default=datetime.date(2021, 11, 3), verbose_name=datetime.date(2021, 11, 3)),
        ),
    ]
