# Generated by Django 3.2 on 2021-11-02 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211103_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date(2021, 11, 3), verbose_name=datetime.date(2021, 11, 3))),
                ('Closing', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Poning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date(2021, 11, 3), verbose_name=datetime.date(2021, 11, 3))),
                ('Opaning', models.CharField(max_length=100)),
            ],
        ),
    ]
