# Generated by Django 3.2 on 2021-11-02 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_closing_poning'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poning',
            new_name='Opaning',
        ),
    ]
