# Generated by Django 3.2.6 on 2021-11-04 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_poning_opaning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closing',
            name='Date',
            field=models.DateField(default=datetime.date(2021, 11, 4), verbose_name=datetime.date(2021, 11, 4)),
        ),
        migrations.AlterField(
            model_name='credit',
            name='Date',
            field=models.DateField(default=datetime.date(2021, 11, 4), verbose_name=datetime.date(2021, 11, 4)),
        ),
        migrations.AlterField(
            model_name='debit',
            name='Date',
            field=models.DateField(default=datetime.date(2021, 11, 4), verbose_name=datetime.date(2021, 11, 4)),
        ),
        migrations.AlterField(
            model_name='opaning',
            name='Date',
            field=models.DateField(default=datetime.date(2021, 11, 4), verbose_name=datetime.date(2021, 11, 4)),
        ),
        migrations.AlterField(
            model_name='opaning',
            name='Opaning',
            field=models.IntegerField(),
        ),
    ]
